import type { Task } from "@/types";

export type { Task };

const ROUTER = "/webhook/router";

export const TASKS: Task[] = [
  {
    id: "ocr-image",
    label: "OCR — Image",
    description: "Extrait le texte d'une image (JPG, PNG, WEBP)",
    icon: "ScanText",
    webhookPath: ROUTER,
    inputType: "image",
    inputLabel: "Glisse une image ou clique pour sélectionner",
  },
  {
    id: "extract-pdf",
    label: "Extraction — PDF",
    description: "Extrait le contenu textuel d'un fichier PDF",
    icon: "FileText",
    webhookPath: ROUTER,
    inputType: "pdf",
    inputLabel: "Glisse un PDF ou clique pour sélectionner",
  },
  {
    id: "extract-file",
    label: "Extraction — Fichier",
    description: "Extrait et formate les données d'un fichier CSV, TXT ou JSON",
    icon: "FileSpreadsheet",
    webhookPath: ROUTER,
    inputType: "file",
    inputLabel: "Glisse un fichier CSV, TXT ou JSON",
  },
  {
    id: "summarize",
    label: "Résumé de texte",
    description: "Génère un résumé structuré d'un texte long",
    icon: "AlignLeft",
    webhookPath: ROUTER,
    inputType: "text",
    inputLabel: "Texte à résumer",
    inputPlaceholder: "Colle ton texte ici...",
  },
  {
    id: "translate",
    label: "Traduction",
    description: "Traduit un texte en français ou en anglais",
    icon: "Languages",
    webhookPath: ROUTER,
    inputType: "text",
    inputLabel: "Texte à traduire",
    inputPlaceholder: "Colle ton texte ici...",
  },
  {
    id: "classify",
    label: "Classification",
    description: "Trouve les mots les plus utilisés dans le texte",
    icon: "Tag",
    webhookPath: ROUTER,
    inputType: "text",
    inputLabel: "Texte à classifier",
    inputPlaceholder: "Colle ton texte ou document ici...",
    outputFormats: [
      { id: "texte", label: "Texte" },
      { id: "json", label: "JSON" },
    ],
  },
  {
    id: "stats",
    label: "Statistiques",
    description: "Compte les mots, caractères, phrases et le temps de lecture",
    icon: "BarChart2",
    webhookPath: ROUTER,
    inputType: "text",
    inputLabel: "Texte à analyser",
    inputPlaceholder: "Colle ton texte ici...",
    outputFormats: [
      { id: "texte", label: "Texte" },
      { id: "json", label: "JSON" },
    ],
  },
  {
    id: "csv-json",
    label: "CSV → JSON",
    description: "Convertit un tableau CSV en JSON formaté et structuré",
    icon: "Table",
    webhookPath: ROUTER,
    inputType: "text",
    inputLabel: "Données CSV",
    inputPlaceholder: "nom,age,ville\nAlice,30,Paris\nBob,25,Lyon",
  },
  {
    id: "spellcheck",
    label: "Correcteur",
    description: "Détecte les fautes d'orthographe et propose des corrections",
    icon: "SpellCheck",
    webhookPath: ROUTER,
    inputType: "text",
    inputLabel: "Texte à corriger",
    inputPlaceholder: "Colle ton texte ici...",
  },
  {
    id: "detect-lang",
    label: "Détection de langue",
    description: "Identifie la langue du texte parmi FR, EN, ES, DE, IT et plus",
    icon: "Globe",
    webhookPath: ROUTER,
    inputType: "text",
    inputLabel: "Texte à analyser",
    inputPlaceholder: "Colle ton texte ici...",
  },
  {
    id: "extract-invoice",
    label: "Extraction Facture",
    description: "Extrait N° facture, date, montant HT/TTC, TVA, SIRET depuis un PDF ou photo",
    icon: "Receipt",
    webhookPath: ROUTER,
    inputType: "document",
    inputLabel: "Glisse une facture (PDF ou photo)",
    outputFormats: [
      { id: "texte", label: "Texte" },
      { id: "json", label: "JSON" },
      { id: "csv", label: "CSV" },
    ],
  },
  {
    id: "extract-form",
    label: "Extraction Formulaire",
    description: "Lit une photo de carnet ou formulaire et extrait Nom, Prénom, Tél, Email, Adresse",
    icon: "ClipboardList",
    webhookPath: ROUTER,
    inputType: "image",
    inputLabel: "Glisse une photo du carnet ou formulaire",
    outputFormats: [
      { id: "texte", label: "Texte" },
      { id: "json", label: "JSON" },
      { id: "csv", label: "CSV" },
    ],
  },
  {
    id: "custom",
    label: "Webhook custom",
    description: "Appelle un webhook n8n avec un payload JSON libre",
    icon: "Zap",
    webhookPath: "/webhook/custom",
    inputType: "text",
    inputLabel: "Payload JSON",
    inputPlaceholder: '{ "key": "value" }',
  },
];
